import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Script from "next/script";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="selection:bg-black/25">
      <body className={`${bricolageGrotesque.className} antialiased`}>
        <Navbar />
        {children}
        <Script
          src="https://tracking.arsenic.cv/api/script.js"
          data-site-id="1d1f08109333"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
